### ISSUE TITLE
Mods -> Mods language and country codes (Trello 148)

### ISSUE THREAD

**Issue by janjouketjalsma** [LeidenUniversityLibrary/islandora_metadata_synchronization#1]
Example MODS records containing codes
[MODS Record.zip](https://github.com/LeidenUniversityLibrary/islandora_metadata_synchronization/files/1715740/MODS.Record.zip)

https://trello.com/c/lPY3dly6/187-148-land-en-taal-code-vervangen-door-de-engelstalige-naam-in-de-solr-index

**Comment by lucasvanschaik** [comment]
Solved in 4e539be8ce82a33d084e738b192637e0a952a8d7
